# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/HEAD/configuration-schema.json
package: v1
generate:
  gorilla-server: true
  strict-server: true
  embedded-spec: true
output: ../backends/pkg/reconciler/eventmesh/v1/server.gen.go
compatibility:
  apply-gorilla-middleware-first-to-last: true
